-- ============================================================================
-- ARCHIVO RETIRADO - NO EJECUTES ESTO
-- ============================================================================
--
-- Este archivo era un borrador del primer prototipo. Creaba una tabla
-- `barberos` que ningún código ha usado nunca: la tabla real siempre fue
-- `trabajadores`. Ejecutarlo no produce una base utilizable y además deja
-- `barberos` ahí, con datos sueltos.
--
-- Usa uno de estos en su lugar:
--
--   · Base de datos NUEVA  ->  supabase-schema.sql
--   · Base ya con datos    ->  supabase-migracion-v2.sql
--                              y luego supabase-migracion-v3.sql
--
-- La documentación está en README.md.
